from __future__ import annotations

from datetime import timedelta

from django.db import models
from django.db.models import Manager
from django.utils import timezone

from aso.scoring import calc_opportunity, classify_keyword, get_targeting_advice


class App(models.Model):
    """
    Represents one of the user's iOS apps.

    Used for organizing keywords into groups — each keyword can
    optionally be associated with an app.

    When added via App Store lookup, track_id stores the iTunes
    numeric ID so we can find the app's rank in search results.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    keywords: Manager[Keyword]

    name = models.CharField(max_length=200)
    bundle_id = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="e.g., com.example.myapp",
    )
    track_id = models.BigIntegerField(
        null=True,
        blank=True,
        unique=True,
        help_text="iTunes trackId — used for rank tracking in search results",
    )
    store_url = models.URLField(
        blank=True,
        default="",
        help_text="App Store URL",
    )
    icon_url = models.URLField(
        blank=True,
        default="",
        help_text="App icon URL from iTunes",
    )
    seller_name = models.CharField(
        max_length=200,
        blank=True,
        default="",
        help_text="Developer/publisher name",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Keyword(models.Model):
    """
    A keyword being tracked for ASO research.

    Can optionally be linked to an App for categorization.
    """

    id: int  # Auto-generated by Django, declared for type checkers
    results: Manager[SearchResult]

    keyword = models.CharField(max_length=200)
    app = models.ForeignKey(
        App,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="keywords",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("keyword", "app")
        ordering = ["-created_at"]

    def __str__(self):
        if self.app:
            return f"{self.keyword} ({self.app.name})"
        return self.keyword


class SearchResult(models.Model):
    """
    Stores the result of a keyword search at a point in time.

    Contains popularity score (from Apple), difficulty score (calculated),
    and the raw competitor data from iTunes Search API.
    """

    id: int  # Auto-generated by Django, declared for type checkers

    keyword = models.ForeignKey(
        Keyword,
        on_delete=models.CASCADE,
        related_name="results",
    )
    popularity_score = models.IntegerField(
        null=True,
        blank=True,
        help_text="1-100 estimated popularity score.",
    )
    difficulty_score = models.IntegerField(
        help_text="1-100 calculated difficulty score",
    )
    difficulty_breakdown = models.JSONField(
        default=dict,
        help_text="Component scores breakdown",
    )
    competitors_data = models.JSONField(
        default=list,
        help_text="Array of top competitor app dicts from iTunes",
    )
    app_rank = models.IntegerField(
        null=True,
        blank=True,
        help_text="App's 1-indexed rank in top-200 iTunes results (null if not found)",
    )
    country = models.CharField(
        max_length=5,
        default="us",
        help_text="Country code used for this search",
    )
    classification = models.CharField(
        max_length=20,
        default="Moderate",
        help_text="Keyword classification label from classify_keyword()",
    )
    searched_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-searched_at"]

    def __str__(self):
        return f"{self.keyword.keyword} — {self.searched_at:%Y-%m-%d %H:%M}"

    @classmethod
    def upsert_today(cls, keyword, country, **fields):
        """
        Create or replace today's result for a keyword+country pair.

        If a result already exists for today, delete it and create a fresh one.
        This ensures exactly one data point per keyword per country per day.
        """
        today_start = timezone.now().replace(hour=0, minute=0, second=0, microsecond=0)
        today_end = today_start + timedelta(days=1)
        cls.objects.filter(
            keyword=keyword,
            country=country,
            searched_at__gte=today_start,
            searched_at__lt=today_end,
        ).delete()
        return cls.objects.create(keyword=keyword, country=country, **fields)

    def save(self, *args, **kwargs):
        """Auto-compute classification from popularity + difficulty on save."""
        self.classification = classify_keyword(
            self.popularity_score or 0, self.difficulty_score
        )
        super().save(*args, **kwargs)

    @property
    def difficulty_label(self):
        """Human-readable difficulty interpretation."""
        score = self.difficulty_score
        if score <= 15:
            return "Very Easy"
        elif score <= 35:
            return "Easy"
        elif score <= 55:
            return "Moderate"
        elif score <= 75:
            return "Hard"
        elif score <= 90:
            return "Very Hard"
        return "Extreme"

    @property
    def difficulty_color(self):
        """Tailwind color class for the difficulty score."""
        score = self.difficulty_score
        if score <= 15:
            return "text-green-400"
        elif score <= 35:
            return "text-green-300"
        elif score <= 55:
            return "text-yellow-400"
        elif score <= 75:
            return "text-orange-400"
        elif score <= 90:
            return "text-red-400"
        return "text-red-600"

    @property
    def opportunity_score(self):
        """Computed opportunity score from popularity and difficulty."""
        return calc_opportunity(self.popularity_score or 0, self.difficulty_score)

    @property
    def targeting_advice(self):
        """Return (icon, label, css_classes, description) for ASO targeting."""
        return get_targeting_advice(self.popularity_score, self.difficulty_score)
